### ISSUE TITLE
CMakelists.txt file needs to be renamed to CMakeLists.txt

### ISSUE THREAD

**Issue by urajendran** [andremueller/vcpkg-template#1]
When I cloned the template in Linux and tried the build.sh I get an error 

CMake Error: The source directory "/vcpkg-template" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

Looks like the CMakelists.txt file needs to be renamed CMakeLists.txt

**Comment by andremueller** [comment]
Thank you very much. Fixed in latest commit.
